spring.application.name=filmorate
# connect bd
#URL for connection
spring.datasource.url=jdbc:postgresql://localhost:5432/filmorate
#login for access
spring.datasource.username=kitty
#password
spring.datasource.password=purr
#name driver class
spring.datasource.driver-class-name=org.postgresql.Driver
